version: '3'
services:
  # app service for your backend
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: ./docker/dev/Dockerfile
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_URI: ${DATABASE_URI}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database

  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    command: mongod --quiet --logpath /dev/null 

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 12345
    