version: '3'
services:
  # app service for your backend
  app:
    build:
      context: ./
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database
    volumes:
      - .:/app

  database:
    image: mongo:6.0
    restart: always
    ports:
      - '27017:27017'
    command: mongod --quiet --logpath /dev/null 

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 12345
networks:
  api:
